"""Intent of IDTA 02017 Asset Interfaces Description v1.0 -> v1.1.

v1.1 gives the entries of several lists an idShort. D1 and D2 rebuild the existing entries under their
names; the paths are spelled out here. D4 concerns the lists of the bindings new in v1.1: the
completion creates list entries without idShort and cannot name an entry once it has children, so the
owner creates every named entry of v1.1 that v1.0 lacks, together with its missing ancestors; these
items are read off v1.1.

    uv run python chains/generators/aid.py
"""

from __future__ import annotations

from _common import ID, header, item, load, write

from tcn.core.metamodel import mand
from tcn.core.model import Id, Template

PRE = "ressources/Templates/IDTA 02017-1-0-1_Template_Asset Interfaces Description.json"
POST = "ressources/Templates/IDTA 02017-1-1_Template_Asset Interfaces Description.json"
URI = "https://github.com/admin-shell-io/submodel-templates/tree/main/published/Asset%20Interfaces%20Description/1/1"
LIST = "SubmodelElementList"

COMMENT = """# Template Change Notification: IDTA 02017 Asset Interfaces Description v1.0 -> v1.1 (intent, generated)
#
# This file states the intent of the revision. `uv run tcn owner complete` appends the mechanical
# completion; the result is aid_1.0_to_1.1.yaml. Generated by chains/generators/aid.py, which spells
# out the paths of D1 and D2 and reads the entries of D4 off v1.1.
# The change log of v1.1 (Annex F) lists the new OPC UA and BACnet bindings, new terms and changed
# semanticIds; all are additions or attribute values, stated by the mechanical completion. Not in the
# change log, taken from the published templates: v1.1 names the entries of the lists security
# (definesSecurityScheme) and htv_headers (htv_header) (D1, D2); MODBUS keeps only
# nosec_sc of its security definitions; scopes of oauth2_sc becomes a list without a template for its
# entries, so that no chain can carry a scope over: its value is reported as removed; the semanticIds
# of base and support change to baseURI and supportContact.
# v1.0 is the bug-fix release 1.0.1, the latest of v1.0; v1.1 is the release before its bug-fix 1.1.1."""


def security_entries() -> list[dict]:
    """D1: each entry of a list security is rebuilt under the name definesSecurityScheme."""
    items = []
    for iface in ("HTTP", "MODBUS", "MQTT"):
        for lst in (f"InterfaceTemplateFor{iface}.EndpointMetadata.security",
                    f"InterfaceTemplateFor{iface}.InteractionMetadata.properties.property_name.forms.security"):
            items += [item("CreateSME", f"{lst}.definesSecurityScheme", SMEType="ReferenceElement"),
                      item("CreateAttr", f"{lst}[1]", AttributeKey="value"),
                      item("Sync", SourceElementPaths=[f"{lst}[0]#value"], TargetElementPaths=[f"{lst}[1]#value"],
                           TransferFunction=ID),
                      item("RemoveSME", f"{lst}[0]")]
    return items


def header_entry() -> list[dict]:
    """D2: the entry of htv_headers is rebuilt under the name htv_header."""
    h = "InterfaceTemplateForHTTP.InteractionMetadata.properties.property_name.forms.htv_headers"
    return [item("CreateSME", f"{h}.htv_header", SMEType="SubmodelElementCollection"),
            item("UpdateParent", f"{h}[0].htv_fieldName", NewParentPath=f"{h}[1]"),
            item("UpdateParent", f"{h}[0].htv_fieldValue", NewParentPath=f"{h}[1]"),
            item("CreateQual", f"{h}[1]", QualifierType="Cardinality"),
            item("UpdateAttr", f"{h}[1]", QualifierType="Cardinality", AttributeKey="valueType", AttributeValue="xs:string"),
            item("CreateAttr", f"{h}[1]", QualifierType="Cardinality", AttributeKey="value"),
            item("Sync", SourceElementPaths=[f"{h}[0]@Cardinality#value"], TargetElementPaths=[f"{h}[1]@Cardinality#value"],
                 TransferFunction=ID),
            item("RemoveQual", f"{h}[0]", QualifierType="Cardinality"),
            item("RemoveSME", f"{h}[0]")]


def named_entries(A: Template, B: Template) -> list[dict]:
    """D4: in document order, the list entries B names and A lacks, with their missing ancestors."""
    have = {(A.path(e), A.E[e].type) for e in A.E}

    def ancestors(e: Id) -> list[Id]:
        chain = []
        while e != B.root:
            chain.append(e)
            e = B.E[e].parent
        return list(reversed(chain))

    created, items, count = set(), [], {}
    for e in B.E:
        p = B.E[e].parent
        if p is None or B.E[p].type != LIST or B.E[e].id_short is None or (B.path(e), B.E[e].type) in have:
            continue
        for a in ancestors(e):
            key = (B.path(a), B.E[a].type)
            if key in have or key in created:
                continue
            parent = B.E[a].parent
            ppath = B.path(parent)
            if B.E[parent].type == LIST:
                path = f"{ppath}.{B.E[a].id_short}" if B.E[a].id_short is not None else f"{ppath}[{count.get(ppath, 0)}]"
                count[ppath] = count.get(ppath, 0) + 1
            else:
                path = f"{ppath}.{B.E[a].id_short}".lstrip(".")
            items.append(item("CreateSME", path, SMEType=B.E[a].type))
            for n in sorted(mand(B.E[a].type)):
                items.append(item("UpdateAttr", B.path(a), AttributeKey=n, AttributeValue=B.A[B.attr(a, n)].value))
            created.add(key)
    return items


def main() -> None:
    write("chains/aid_1.0_to_1.1.intent.yaml", COMMENT, header("AssetInterfacesDescription", PRE, POST, URI), [
        ("D1: the entries of the lists security are named definesSecurityScheme; each is rebuilt under its name, "
         "its reference carried over", "hand", security_entries()),
        ("D2: the entry of the list htv_headers is named htv_header; it is rebuilt under its name", "hand", header_entry()),
        ("D4: the new bindings of v1.1 name the entries of their lists security, bacv_hasNamedMember, bacv_hasValueMap, "
         "iolv_payloadMapping and iolv_enumeratedValues too; these entries are created under their names, with their "
         "missing ancestors", "hand", named_entries(load(PRE), load(POST))),
    ])


if __name__ == "__main__":
    main()
