"""Intent of the bug-fix releases whose only structural correction is that the entries of their lists
no longer carry an idShort (F1).

The intent is the same for all of them and is read off the two templates: every entry of a list that
carries an idShort in v_i and none in v_i+1 is rebuilt. An entry without children is rebuilt by hand
items (a new entry with the mandatory attributes of the old one, value and qualifiers carried over by
Sync, the old entry removed); an entry with children by the rule RenameContainer (hollow-out).

    uv run python chains/generators/bugfix.py
"""

from __future__ import annotations

from _common import ID, header, item, load, write

from tcn.core.metamodel import mand
from tcn.core.model import Id, Template

GITHUB = "https://github.com/admin-shell-io/submodel-templates/tree/main/published"
T = "ressources/Templates"
# name, family, title, v_i, v_i+1, path of the release on GitHub
RELEASES = [
    ("aimc_2.0_to_2.1", "AssetInterfacesMappingConfiguration", "IDTA 02027 Asset Interfaces Mapping Configuration v2.0 -> v2.1",
     f"{T}/IDTA 02027-2-0_Template_AIMC.json", f"{T}/IDTA 02027-2-1_Template_AIMC.json",
     "Asset%20Interfaces%20Mapping%20Configuration/2/1"),
    ("energyflexibility_1.0_to_1.1", "EnergyFlexibilityDataModel", "IDTA 02076 Energy Flexibility Data Model v1.0 -> v1.1",
     f"{T}/IDTA 02076-1-0_Template_EnergyFlexibilityDataModel.json",
     f"{T}/IDTA 02076-1-1_Template_EnergyFlexibilityDataModel.json", "Energy%20Flexibility%20Data%20Model/1/1"),
    ("plantplanning_1.0_to_1.1", "FactoryAutomationDataForPlantPlanning",
     "IDTA 02075 Factory Automation Data for Plant Planning v1.0 -> v1.1",
     f"{T}/IDTA 02075-1-0_Template_FactoryAutomationDataForPlantPlanning.json",
     f"{T}/IDTA 02075-1-1_Template_FactoryAutomationDataForPlantPlanning.json",
     "Factory%20Automation%20Data%20for%20Plant%20Planning/1/1"),
    ("plasticwaste_1.0_to_1.1", "MaterialDataForPlasticWaste", "IDTA 02080 Material Data for Plastic Waste v1.0 -> v1.1",
     f"{T}/IDTA 02080-1-0_Template_Material Data for Plastic Waste.json",
     f"{T}/IDTA 02080-1-1_Template_Material Data for Plastic Waste.json", "Material%20Data%20for%20Plastic%20Waste/1/1"),
    ("opcuaserver_1.0_to_1.1", "OPCUAServerDatasheet", "IDTA 02009 OPC UA Server Datasheet v1.0 -> v1.1",
     f"{T}/IDTA 02009-1-0_Template_OPCUA-Server Datasheet.json", f"{T}/IDTA 02009-1-1_Template_OPCUA-Server Datasheet.json",
     "OPC%20UA%20Server%20Datasheet/1/1"),
    ("pcn_1.0_to_1.1", "ProductChangeNotifications", "IDTA 02036 Product Change Notifications v1.0 -> v1.1",
     f"{T}/IDTA 02036-1-0_Template_ProductChangeNotifications.json",
     f"{T}/IDTA 02036-1-1_Template_ProductChangeNotifications.json", "Product%20Change%20Notifications/1/1"),
    ("qualitycontrol_1.0_to_1.1", "QualityControlForMachining", "IDTA 02049 Quality Control for Machining v1.0 -> v1.1",
     f"{T}/IDTA 02049-1-0_Template_QualityControlForMachining.json",
     f"{T}/IDTA 02049-1-1_Template_QualityControlForMachining.json", "Quality%20Control%20for%20Machining/1/1"),
]

COMMENT = """# Template Change Notification: {title} (intent, generated)
#
# This file states the intent of the revision. `uv run tcn owner complete` expands the rule sections
# in place and appends the mechanical completion; the result is {name}.yaml.
# Generated by chains/generators/bugfix.py from the two templates; the generator states how the intent
# is read off them.
# Bug-fix release: its change log is the list of issues it fixes (#187, #207, #208, #210 of
# admin-shell-io/submodel-templates): the machine-readable artifacts are corrected, the specification
# is carried over unchanged. Its submodel id and administration are those of the previous version.
# F1 is the only structural correction; the qualifier kind (#159), semanticIds and language strings
# are attribute-level corrections, stated by the mechanical completion."""


def unnamed_entries(A: Template, B: Template) -> tuple[list[Id], list[Id]]:
    """Entries of lists that carry an idShort in A and none in B: (without children, with children)."""
    b = {B.path(e): B.E[e] for e in B.E}
    leaves, containers = [], []
    for e in A.E:
        p = A.E[e].parent
        if p is None or A.E[p].type != "SubmodelElementList":
            continue
        path = A.path(e)
        if path in b and A.E[e].id_short is not None and b[path].id_short is None:
            (containers if A.children(e) else leaves).append(e)
    return leaves, containers


def rebuild(A: Template, e: Id) -> list[dict]:
    """Rebuild an entry without children at the end of its list, its values and qualifiers carried over."""
    path = A.path(e)
    new = f"{A.path(A.E[e].parent)}[{len(A.children(A.E[e].parent))}]"
    items = [item("CreateSME", new, SMEType=A.E[e].type)]
    for key in sorted(mand(A.E[e].type)):  # mandatory attributes, as in the entry they replace
        items.append(item("UpdateAttr", new, AttributeKey=key, AttributeValue=A.A[A.attr(e, key)].value))
    for key in ("value", "valueId"):
        if key == "valueId" and A.attr(e, key) is None:
            continue
        if A.attr(e, key) is None:  # the source of Sync has to exist in the template too
            items.append(item("CreateAttr", path, AttributeKey=key))
        items += [item("CreateAttr", new, AttributeKey=key),
                  item("Sync", SourceElementPaths=[f"{path}#{key}"], TargetElementPaths=[f"{new}#{key}"],
                       TransferFunction=ID)]
    for q in A.qualifiers(e):
        k = A.Q[q].qtype
        items += [item("CreateQual", new, QualifierType=k),
                  item("UpdateAttr", new, QualifierType=k, AttributeKey="valueType",
                       AttributeValue=A.A[A.attr(q, "valueType")].value)]
        if A.attr(q, "value") is not None:
            items += [item("CreateAttr", new, QualifierType=k, AttributeKey="value"),
                      item("Sync", SourceElementPaths=[f"{path}@{k}#value"], TargetElementPaths=[f"{new}@{k}#value"],
                           TransferFunction=ID)]
        items.append(item("RemoveQual", path, QualifierType=k))
    return items + [item("RemoveSME", path)]


def main() -> None:
    for name, family, title, pre, post, release in RELEASES:
        A, B = load(pre), load(post)
        leaves, containers = unnamed_entries(A, B)
        sections = []
        if leaves:
            sections.append(("F1: the entries of the lists no longer carry an idShort; entries without children are "
                             "rebuilt, their values carried over", "hand", [i for e in leaves for i in rebuild(A, e)]))
        if containers:
            sections.append(("F1: the entries of the lists no longer carry an idShort; entries with children are "
                             "rebuilt by hollow-out", "rule", {"RenameContainer": {A.path(e): None for e in containers}}))
        write(f"chains/{name}.intent.yaml", COMMENT.format(title=title, name=name),
              header(family, pre, post, f"{GITHUB}/{release}"), sections)


if __name__ == "__main__":
    main()
