"""Intent of IDTA 02004 Handover Documentation v1.2 -> v2.0.

The intent is stated here item by item; the generator only spells out the long paths of the
restructured documents.

    uv run python chains/generators/handover.py
"""

from __future__ import annotations

from _common import ID, header, item, write

PRE = "ressources/Templates/IDTA 02004-1-2_Template_Handover Documentation.json"
POST = "ressources/Templates/IDTA 02004-2-0_Template_HandoverDocumentation.json"
URI = "https://github.com/admin-shell-io/submodel-templates/tree/main/published/Handover%20Documentation/2/0"
D = "Document__00__"
N = "Documents[0]"
DV_OLD = f"{D}.DocumentVersion__00__"
DV = f"{N}.DocumentVersions[0]"

COMMENT = """# Template Change Notification: IDTA 02004 Handover Documentation v1.2 -> v2.0 (intent, generated)
#
# This file states the intent of the revision. `uv run tcn owner complete` expands the rule sections
# in place and appends the mechanical completion; the result is handover_1.2_to_2.0.yaml.
# Generated by chains/generators/handover.py, which spells out the long paths; the items are
# those of the intent.
# The numbers in the titles refer to the change log of IDTA 02004-2-0 (Annex C, Table 15): (5)
# "Addition and correction of SML/SMC elements", (6) DocumentVersionId -> Version, (7) Summary ->
# Description, (9) ValueId -> DocumentIdentifier; the updated ECLASS IRDIs (2) are stated by the
# mechanical completion. Not in the change log, taken from the published templates: the rename of the
# root idShort HandoverDocumentation__00__, the removal of numberOfDocuments, the renames IsPrimary ->
# DocumentIsPrimary, SubTitle -> Subtitle, OrganizationName -> OrganizationShortName, KeyWords
# becoming optional, and the change of the cardinality vocabulary (H15).
# A DigitalFile/PreviewFile of v1.2 is a collection of MimeType and DocumentPath, a File of v2.0
# carries both as contentType and value (H8, H9)."""


def qual(new, qtype, source, transfer=ID):
    """Relocate the qualifier `qtype` of `source` to `new` (value linked by Sync); `new` may carry it
    under another type."""
    old_type, new_type = qtype if isinstance(qtype, tuple) else (qtype, qtype)
    return [item("CreateQual", new, QualifierType=new_type),
            item("UpdateAttr", new, QualifierType=new_type, AttributeKey="valueType", AttributeValue="xs:string"),
            item("CreateAttr", new, QualifierType=new_type, AttributeKey="value"),
            item("Sync", None, SourceElementPaths=[f"{source}@{old_type}#value"], TargetElementPaths=[f"{new}@{new_type}#value"],
              TransferFunction=transfer)]


def drop_quals(path, *qtypes):
    return [item("RemoveQual", path, QualifierType=q) for q in qtypes]


def new_list(path, element_type, value_type=None):
    items = [item("CreateSME", path, SMEType="SubmodelElementList"),
             item("UpdateAttr", path, AttributeKey="typeValueListElement", AttributeValue=element_type)]
    if value_type:
        items += [item("CreateAttr", path, AttributeKey="valueTypeListElement"),
                  item("UpdateAttr", path, AttributeKey="valueTypeListElement", AttributeValue=value_type)]
    return items


def link_semantics(old, new):
    """The new element takes over the semanticId of the element it replaces (the semanticId of v2.0
    is set by the completion), so that every realisation of the old element yields one new element."""
    return [item("CreateAttr", new, AttributeKey="semanticId"),
            item("Sync", None, SourceElementPaths=[f"{old}#semanticId"], TargetElementPaths=[f"{new}#semanticId"], TransferFunction=ID)]


to_entries = {"Kind": "ValueMap", "Pairs": {"ZeroToMany": "OneToMany", "OneToMany": "OneToMany"}}


def main() -> None:
    sections = []
    # H3: documents become entries of the list Documents
    items = new_list("Documents", "SubmodelElementCollection") + [item("CreateSME", N, SMEType="SubmodelElementCollection")]
    items += link_semantics(D, N)
    items += qual(N, ("Cardinality", "SMT/Cardinality"), D, to_entries)
    sections.append(("H3: Document__00__ becomes an entry of the list Documents (5)", "hand", items))

    # H4: document ids
    old = f"{D}.DocumentId__00__"
    new = f"{N}.DocumentIds[0]"
    items = new_list(f"{N}.DocumentIds", "SubmodelElementCollection") + [item("CreateSME", new, SMEType="SubmodelElementCollection")]
    items += [item("UpdateIdShort", f"{old}.ValueId", NewIdShort="DocumentIdentifier"),
              item("UpdateIdShort", f"{old}.IsPrimary", NewIdShort="DocumentIsPrimary")]
    items += [item("UpdateParent", f"{old}.{c}", NewParentPath=new) for c in ("DocumentDomainId", "DocumentIdentifier", "DocumentIsPrimary")]
    items += qual(new, ("Cardinality", "SMT/Cardinality"), old) + drop_quals(old, "Cardinality") + [item("RemoveSME", old)]
    sections.append(("H4: DocumentId__00__ becomes an entry of the list DocumentIds; ValueId becomes DocumentIdentifier (9), "
                     "IsPrimary becomes DocumentIsPrimary", "hand", items))

    # H5: classifications
    old = f"{D}.DocumentClassification__00__"
    new = f"{N}.DocumentClassifications[0]"
    items = new_list(f"{N}.DocumentClassifications", "SubmodelElementCollection")
    items += [item("CreateSME", new, SMEType="SubmodelElementCollection")]
    items += [item("UpdateParent", f"{old}.{c}", NewParentPath=new) for c in ("ClassId", "ClassName", "ClassificationSystem")]
    items += qual(new, ("Cardinality", "SMT/Cardinality"), old) + drop_quals(old, "Cardinality") + [item("RemoveSME", old)]
    sections.append(("H5: DocumentClassification__00__ becomes an entry of the list DocumentClassifications", "hand", items))

    # H6: versions
    items = new_list(f"{N}.DocumentVersions", "SubmodelElementCollection") + [item("CreateSME", DV, SMEType="SubmodelElementCollection")]
    renames = {"DocumentVersionId": "Version", "SubTitle": "Subtitle", "Summary": "Description",
               "OrganizationName": "OrganizationShortName"}
    items += [item("UpdateIdShort", f"{DV_OLD}.{a}", NewIdShort=b) for a, b in renames.items()]
    items += [item("UpdateParent", f"{DV_OLD}.{c}", NewParentPath=DV) for c in
              ("Version", "Title", "Subtitle", "Description", "KeyWords", "StatusSetDate", "StatusValue",
               "OrganizationShortName", "OrganizationOfficialName")]
    sections.append(("H6: DocumentVersion__00__ becomes an entry of the list DocumentVersions; DocumentVersionId becomes "
                     "Version (6), Summary becomes Description (7), SubTitle becomes Subtitle, OrganizationName becomes "
                     "OrganizationShortName", "hand", items))

    # H7: languages
    old = f"{DV_OLD}.Language__00__"
    lst = f"{DV}.Language"
    items = new_list(lst, "Property", "xs:string") + [
        item("CreateSME", f"{lst}[0]", SMEType="Property"),
        item("UpdateAttr", f"{lst}[0]", AttributeKey="valueType", AttributeValue="xs:string"),
        item("CreateAttr", f"{lst}[0]", AttributeKey="value"),
        item("Sync", None, SourceElementPaths=[f"{old}#value"], TargetElementPaths=[f"{lst}[0]#value"], TransferFunction=ID)]
    items += qual(f"{lst}[0]", ("Cardinality", "SMT/Cardinality"), old) + qual(f"{lst}[0]", "ExampleValue", old)
    items += drop_quals(old, "Cardinality", "ExampleValue", "AllowedIdShort") + [item("RemoveSME", old)]
    sections.append(("H7: the repeatable property Language__00__ becomes the list Language; each language is one entry", "hand", items))

    # H8: files
    for old_name, new_path, title in (
            ("DigitalFile__00__", f"{DV}.DigitalFiles[0]", "H8: DigitalFile__00__ (MimeType, DocumentPath) becomes an entry of "
                                                           "the list DigitalFiles of type File"),
            ("PreviewFile__00__", f"{DV}.PreviewFile", "H9: PreviewFile__00__ (MimeType, DocumentPath) becomes the File PreviewFile")):
        old = f"{DV_OLD}.{old_name}"
        items = new_list(f"{DV}.DigitalFiles", "File") if old_name == "DigitalFile__00__" else []
        items += [item("CreateSME", new_path, SMEType="File"),
                  item("CreateAttr", new_path, AttributeKey="value"),
                  item("Sync", None, SourceElementPaths=[f"{old}.DocumentPath#value"], TargetElementPaths=[f"{new_path}#value"],
                    TransferFunction=ID),
                  item("CreateAttr", new_path, AttributeKey="contentType"),
                  item("Sync", None, SourceElementPaths=[f"{old}.MimeType#value"], TargetElementPaths=[f"{new_path}#contentType"],
                    TransferFunction=ID)]
        quals = ["Cardinality", "ExampleValue", "AllowedIdShort"]
        items += qual(new_path, ("Cardinality", "SMT/Cardinality"), old) + qual(new_path, "ExampleValue", old)
        items += qual(new_path, "AllowedIdShort", old)
        for c in ("MimeType", "DocumentPath"):
            items += drop_quals(f"{old}.{c}", "Cardinality") + [item("RemoveSME", f"{old}.{c}")]
        items += drop_quals(old, *quals) + [item("RemoveSME", old)]
        sections.append((title, "hand", items))

    # H10: relations between documents
    for old_name, lst, title in (("RefersTo__00__", "RefersToEntities", "H10"), ("BasedOn__00__", "BasedOnReferences", "H11"),
                                 ("TranslationOf__00__", "TranslationOfEntities", "H12")):
        old = f"{DV_OLD}.{old_name}"
        new = f"{DV}.{lst}[0]"
        items = new_list(f"{DV}.{lst}", "ReferenceElement") + [
            item("CreateSME", new, SMEType="ReferenceElement"),
            item("CreateAttr", old, AttributeKey="value"),
            item("CreateAttr", new, AttributeKey="value"),
            item("Sync", None, SourceElementPaths=[f"{old}#value"], TargetElementPaths=[f"{new}#value"], TransferFunction=ID)]
        items += qual(new, ("Cardinality", "SMT/Cardinality"), old, to_entries) + qual(new, "AllowedIdShort", old)
        items += drop_quals(old, "Cardinality", "AllowedIdShort") + [item("RemoveSME", old)]
        sections.append((f"{title}: the repeatable reference {old_name} becomes the list {lst}; each reference is one entry", "hand", items))

    old = DV_OLD
    items = link_semantics(old, DV) + qual(DV, ("Cardinality", "SMT/Cardinality"), old, to_entries)
    items += drop_quals(old, "Cardinality") + [item("RemoveSME", old)]
    sections.append(("H6: the emptied DocumentVersion__00__ is removed; at least one version is required", "hand", items))

    # H13: documented entities
    old = f"{D}.DocumentedEntity"
    new = f"{N}.DocumentedEntities[0]"
    items = new_list(f"{N}.DocumentedEntities", "ReferenceElement") + [
        item("CreateSME", new, SMEType="ReferenceElement"),
        item("CreateAttr", old, AttributeKey="value"),
        item("CreateAttr", new, AttributeKey="value"),
        item("Sync", None, SourceElementPaths=[f"{old}#value"], TargetElementPaths=[f"{new}#value"], TransferFunction=ID)]
    items += qual(new, ("Cardinality", "SMT/Cardinality"), old, to_entries) + drop_quals(old, "Cardinality") + [item("RemoveSME", old)]
    items += drop_quals(D, "Cardinality") + [item("RemoveSME", D)]
    sections.append(("H13: the repeatable reference DocumentedEntity becomes the list DocumentedEntities; the emptied "
                     "Document__00__ is removed", "hand", items))

    # H14: entities
    old = "Entity__00__"
    new = "Entities[0]"
    items = new_list("Entities", "Entity") + [item("CreateSME", new, SMEType="Entity"),
                                              item("CreateAttr", new, AttributeKey="entityType"),
                                              item("UpdateAttr", new, AttributeKey="entityType", AttributeValue="CoManagedEntity")]
    items += link_semantics(old, new)
    # the asset the entity stands for is instance data; neither template carries it, so the
    # attributes are created for the link only
    for key in ("globalAssetId", "specificAssetIds"):
        items += [item("CreateAttr", old, AttributeKey=key), item("CreateAttr", new, AttributeKey=key),
                  item("Sync", None, SourceElementPaths=[f"{old}#{key}"], TargetElementPaths=[f"{new}#{key}"],
                       TransferFunction=ID)]
    items += qual(new, ("Cardinality", "SMT/Cardinality"), old, to_entries)
    items += drop_quals(old, "Cardinality") + [item("RemoveSME", old)]
    sections.append(("H14: the repeatable entity Entity__00__ becomes the list Entities; each entity is one entry, "
                     "the asset it stands for carried over", "hand", items))
    sections.append(("H15: the cardinality vocabulary changes from Cardinality to SMT/Cardinality", "rule",
                     {"QualifierTypeRenames": {"Cardinality": "SMT/Cardinality"}}))
    write("chains/handover_1.2_to_2.0.intent.yaml", COMMENT, header("HandoverDocumentation", PRE, POST, URI), sections)


if __name__ == "__main__":
    main()
